version: "3.3"
services:
  prerender:
    build:
      context: prerender/
    labels:
      com.dgyar.title: "Prerender system"
      com.dgyar.description: "Create and manages prerendered pabes"
      com.dgyar.department: "IT"
    environment:
      SERVER_DIR: /root
      CHROME_BIN: /usr/bin/chromium-browser
      CHROME_PATH: /usr/lib/chromium/
      PAGE_DONE_CHECK_INTERVAL: 500
      PAGE_LOAD_TIMEOUT: 20000
      WAIT_AFTER_LAST_REQUEST: 250
    networks:
      - viraweb
  dms:
    build:
      context: dms/
    labels:
      com.dgyar.title: "Domain management system"
      com.dgyar.description: "Create and manages certificates, domains, and dns"
      com.dgyar.department: "IT"
    networks:
      - viraweb
    volumes:
      - type: volume
        source: plufStorage-vol
        target: /var/www/storage
      - type: volume
        source: sites-enabled-vol
        target: /var/www/sites-enabled
  mysql:
    build:
      context: mysql/
    labels:
      com.dgyar.description: "Data node"
      com.dgyar.department: "IT"
    command: --sql_mode=""
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: plufdb
      MYSQL_USER: pluf
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    networks:
      - viraweb
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysql-vol
        target: /var/lib/mysql
  pluf:
    build:
      context: pluf/
    labels:
      com.dgyar.description: "Public webapp interface"
      com.dgyar.department: "IT"
    volumes:
      - type: volume
        source: plufStorage-vol
        target: /var/www/storage
      - type: volume
        source: plufLetsencrypt-vol
        target: /var/www/logs
      - type: volume
        source: sites-enabled-vol
        target: /etc/apache2/sites-enabled
    ports:
      - "80:80"
    networks:
      - viraweb
    depends_on:
      - mysql
  # Backup service
  volumerize:
    container_name: volumerize
    image: blacklabelops/volumerize
    restart: unless-stopped
    environment:
        - 'TZ=Asia/Tehran'
        - 'VOLUMERIZE_SOURCE=/source'
        - 'VOLUMERIZE_TARGET=file:///backup'
        - 'VOLUMERIZE_JOBBER_TIME=0 0 3 * * *'
        - 'VOLUMERIZE_FULL_IF_OLDER_THAN=7D'
        - 'JOB_NAME2=RemoveOldBackups'
        - 'JOB_COMMAND2=/etc/volumerize/remove-older-than 7D --force'
        - 'JOB_TIME2=0 0 * * * *'
    # Add all service volume to volumerize
    # NOTE: for restore data, first stop all container and delete :ro 
    volumes:
        - type: volume
          source: mysql-vol
          target: /source/mysql:ro
        - type: volume
          source: plufLetsencrypt-vol 
          target: /source/letscript:ro
        - type: volume
          source: plufLog-vol
          target: /source/pluflog:ro
        - type: volume
          source: plufStorage-vol
          target: /source/plufstorage:ro
        - type: volume
          source: sites-enabled-vol
          target: /source/siteenable:ro
        - type: bind
          source: /backup
          target: /backup
        - type: volume
          source: backup-cache
          target: /volumerize-cache

networks:
  viraweb:
  
volumes:
  mysql-vol:
    external: false
  plufStorage-vol:
    external: false
  plufLog-vol:
    external: false
  plufLetsencrypt-vol:
    external: false
  sites-enabled-vol:
    external: false
  backup-cache:
    external: false
